# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables

image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
        - step:
            services:
              - docker
            script:
              - docker login appHerzum.azurecr.io -u $AZURE_USER -p  $AZURE_PASS
              
              # Publish auth container
              - docker build -t appHerzum.azurecr.io/mywebapi/api .
              - docker push  appHerzum.azurecr.io/mywebapi/api